FROM ubuntu:18.04

## Basic items setup
ENV quakedir="/opt/aq2"
ENV quakeuser="quaker"
RUN useradd ${quakeuser} -u 1001
RUN mkdir -p ${quakedir}/action/logs
RUN apt-get update && apt-get install wget liblua5.1-0 lua5.1-dev lua5.1 -y

## Get the latest contents
ENV aqtionversion="_AQTION_VERSION_"

RUN wget -q https://github.com/actionquake/distrib/releases/download/${aqtionversion}/aqtion-${aqtionversion}-linux-amd64.tar.gz && tar xvf aqtion-${aqtionversion}-linux-amd64.tar.gz --strip-components=1 -C /opt/aq2/

RUN mkdir -p ${quakedir}/plugins/
COPY server/configs/official/config.lua LICENSE ${quakedir}/
COPY server/configs/official/teamplay.cfg server/configs/official/action.ini server/configs/official/autoexec.cfg server/configs/official/deathmatch.cfg server/configs/official/teamdeathmatch.cfg  LICENSE ${quakedir}/action/
COPY server/configs/official/plugins/* ${quakedir}/plugins/
COPY aq2-entrypoint.sh ${quakedir}

RUN chmod +x ${quakedir}/q2proded ${quakedir}/aq2-entrypoint.sh
RUN chown ${quakeuser} -R ${quakedir}
WORKDIR ${quakedir}
RUN chown ${quakeuser}:${quakeuser} -R /opt/aq2

USER quaker
CMD [ "/opt/aq2/aq2-entrypoint.sh" ]
