FROM ubuntu:18.04
ENV quakedir="/opt/aq2"
ENV quakeuser="quaker"

RUN useradd ${quakeuser} -u 1001
RUN apt-get update && apt-get install wget liblua5.1-0 lua5.1-dev lua5.1 -y

RUN mkdir -p ${quakedir}/plugins/
COPY action LICENSE ${quakedir}/
COPY aq2-entrypoint.sh ${quakedir}

RUN chmod +x ${quakedir}/q2proded ${quakedir}/aq2-entrypoint.sh
RUN chown ${quakeuser} -R ${quakedir}
WORKDIR ${quakedir}
RUN chown ${quakeuser}:${quakeuser} -R /opt/aq2

USER quaker
CMD [ "/opt/aq2/aq2-entrypoint.sh" ]
